name: Auto Update Sidebar

on:
  push:
    branches:
      - main  
    paths-ignore:
      - '_sidebar.md' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予 Action 写入仓库的权限

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Sidebar Script
        run: python generate_sidebar.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update sidebar [skip ci]"
          file_pattern: '_sidebar.md'